### PR TITLE
Fix travis build

### PR DESCRIPTION
**Pull request by hongchangwu**

### CODE REVIEW

**Comment by hongchangwu** [comment]
Ping

**Comment by sol** [comment]
@hongchangwu Sorry for the delay.  I'm still puzzled why the original build fails.  Did you pin that down?

**Comment by hongchangwu** [comment]
In the original build `cabal-install` tried to build packages that should ship with GHC (e.g. `binary` and `bytestring`) and the versions resolved were incorrect. See https://github.com/kolmodin/binary/issues/121 for more info. In any case the default `haskell` package shipped with travis is terrible and it's better to use more controlled sandboxes.

**Comment by hongchangwu** [comment]
@sol need any more clarification? The current travis setup is broken and will prevent any further PRs. See #11.

**Comment by sol** [comment]
Yes, I'm still puzzled what exactly causes the build to fail.  We see the symptoms, but there has to be an underlying reason.

We could just merge this and forget about it, but I would rather first understand what exactly causes the build to fail, esp. since this effects every Hspec user who uses the default travis Haskell support.

**Comment by sol** [comment]
```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.8.4
```

```
$ cabal --version
cabal-install version 1.18.0.2
using version 1.18.1.5 of the Cabal library 
```

```
$ cabal install --only-dependencies --enable-tests --dry-run
Resolving dependencies...
In order, the following would be installed (use -v for more details):
bytestring-0.10.2.0 (latest: 0.10.8.1)
binary-0.8.4.1
bytestring-builder-0.10.4.0 (latest: 0.10.8.1.0)
call-stack-0.1.0
HUnit-1.5.0.0
hspec-expectations-0.8.2
random-1.1
stm-2.4.4.1
async-2.1.1
text-1.0.0.1 (latest: 1.2.2.1)
hashable-1.2.5.0
nats-1.1.1
transformers-0.5.2.0
primitive-0.6.2.0
tf-random-0.5
transformers-compat-0.5.1.4
tagged-0.8.5
unix-2.7.2.1
ansi-terminal-0.6.2.3
directory-1.3.0.1
hspec-discover-2.4.1
setenv-0.1.1.3
unordered-containers-0.2.7.2
semigroups-0.18.2
QuickCheck-2.9.2
quickcheck-io-0.1.4
hspec-core-2.4.1
hspec-2.4.1
```

**Comment by sol** [comment]
```
$ cabal --version
cabal-install version 1.24.0.2
compiled using version 1.24.2.0 of the Cabal library
```
```
$ cabal install --only-dependencies --enable-tests --dry-run
Resolving dependencies...
In order, the following would be installed (use -v for more details):
ansi-terminal-0.6.2.3
call-stack-0.1.0
HUnit-1.5.0.0
hspec-discover-2.4.1
hspec-expectations-0.8.2
random-1.1
setenv-0.1.1.3
stm-2.4.4.1
async-2.1.1
text-1.2.2.1
hashable-1.2.5.0
nats-1.1.1
transformers-0.5.2.0
primitive-0.6.2.0
tf-random-0.5
transformers-compat-0.5.1.4
tagged-0.8.5
unordered-containers-0.2.7.2
semigroups-0.18.2
QuickCheck-2.9.2
quickcheck-io-0.1.4
hspec-core-2.4.1
hspec-2.4.1
```

**Comment by sol** [comment]
The build fails on default Travis, which uses GHC 7.8.4.  However, with your PR the build succeeds with GHC 7.8.4.

There are multiple problems here:

- `cabal-install-1.18.0.2` (which is used on Travis) tries to reinstall packages that come with GHC.  HVR repos use `cabal-install-1.18.0.4`, which seems to be fine.

- `binary-0.8.4.1` does not build with GHC 7.8.4

**Comment by sol** [comment]
The right thing would be to fix this in `travis-ci/travis-cookbooks`.  But I'm not inclined to work on the Chef recipes.  So let's go this.

**Pull request merged**
